name: ClearChat
main: me.phil14052.ClearChat3_0.ClearChat
version: 3.2.3
author: phil14052
description: ClearChat controls everything on your server with clearing the chat. It can help you with auto clearing, join cleaning, etc. It also has an API, so servers can add their own clears.
softdepend: [PlaceholderAPI]
commands:
  clearchat:
    description: ClearChat Plugin Main Command
    aliases: cc